In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [2]:
df=pd.read_csv("C:\\Users\\Yuvaraj_Subramanian\\Downloads\\Projects\\Motion Capture Hand Posture\\UpdatedPostures.csv")
df.head(2)

Class  User         X0         Y0         Z0         X1        Y1  \
0      1     0  54.263880  71.466776 -64.807709  76.895635  42.46250   
1      1     0  56.527558  72.266609 -61.935252  39.135978  82.53853   

          Z1         X2         Y2         Z2         X3         Y3  \
0 -72.780545  36.621229  81.680557 -52.919272  85.232264  67.749220   
1 -49.596509  79.223743  43.254091 -69.982489  87.450873  68.400808   

          Z3         X4         Y4         Z4         X5         Y5  \
0 -73.684130  59.188576  10.678936 -71.297781  86.807789  72.701233   
1 -70.703991  61.587452  11.779919 -68.827418  86.807789  72.701233   

          Z5   X6   Y6   Z6   X7   Y7   Z7   X8   Y8   Z8   X9   Y9   Z9  X10  \
0 -71.373391  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1 -71.373391  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   Y10  Z10  
0  0.0  0.0  
1  0.0  0.0

In [3]:
df.drop('User',axis=1,inplace=True)

In [4]:
df.head(2)

Class         X0         Y0         Z0         X1        Y1         Z1  \
0      1  54.263880  71.466776 -64.807709  76.895635  42.46250 -72.780545   
1      1  56.527558  72.266609 -61.935252  39.135978  82.53853 -49.596509   

          X2         Y2         Z2         X3         Y3         Z3  \
0  36.621229  81.680557 -52.919272  85.232264  67.749220 -73.684130   
1  79.223743  43.254091 -69.982489  87.450873  68.400808 -70.703991   

          X4         Y4         Z4         X5         Y5         Z5   X6   Y6  \
0  59.188576  10.678936 -71.297781  86.807789  72.701233 -71.373391  0.0  0.0   
1  61.587452  11.779919 -68.827418  86.807789  72.701233 -71.373391  0.0  0.0   

    Z6   X7   Y7   Z7   X8   Y8   Z8   X9   Y9   Z9  X10  Y10  Z10  
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

#### Using the columns that have atleast more than 50% data which is done as a part of feature selection

In [7]:
dfn=df.iloc[:,0:25]

In [8]:
dfn.head(2)

Class         X0         Y0         Z0         X1        Y1         Z1  \
0      1  54.263880  71.466776 -64.807709  76.895635  42.46250 -72.780545   
1      1  56.527558  72.266609 -61.935252  39.135978  82.53853 -49.596509   

          X2         Y2         Z2         X3         Y3         Z3  \
0  36.621229  81.680557 -52.919272  85.232264  67.749220 -73.684130   
1  79.223743  43.254091 -69.982489  87.450873  68.400808 -70.703991   

          X4         Y4         Z4         X5         Y5         Z5   X6   Y6  \
0  59.188576  10.678936 -71.297781  86.807789  72.701233 -71.373391  0.0  0.0   
1  61.587452  11.779919 -68.827418  86.807789  72.701233 -71.373391  0.0  0.0   

    Z6   X7   Y7   Z7  
0  0.0  0.0  0.0  0.0  
1  0.0  0.0  0.0  0.0

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, roc_curve, confusion_matrix, classification_report, accuracy_score

In [10]:
X=dfn.drop('Class',axis=1)
y=dfn['Class']

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30,random_state=42)

### Building ML Algorithms

#### Logisitic Regression

In [13]:
import warnings
warnings.filterwarnings('ignore')

In [14]:
from sklearn.linear_model import LogisticRegression

In [15]:
lr=LogisticRegression(fit_intercept=True,solver='liblinear', multi_class='ovr')

In [16]:
lr.fit(X_train,y_train)
y_train_pred=lr.predict(X_train)
y_train_prob=lr.predict_proba(X_train)
print("Confusion Matrix - Train: ",'\n',confusion_matrix(y_train,y_train_pred))
print("Overall Accuracy - Train: ",accuracy_score(y_train,y_train_pred))
print('ROC score: ',roc_auc_score(y_train, y_train_prob, multi_class='ovr'))
print('Classification Report- ',classification_report(y_train, y_train_pred))

y_test_pred=lr.predict(X_test)
y_test_prob=lr.predict_proba(X_test)

print('\n')
print("Confusion Matrix - Train: ",'\n',confusion_matrix(y_test,y_test_pred))
print("Overall Accuracy - Train: ",accuracy_score(y_test,y_test_pred))
print('ROC score: ',roc_auc_score(y_test, y_test_prob, multi_class='ovr'))
print('Classification Report- ',classification_report(y_test, y_test_pred))


Confusion Matrix - Train:  
 [[10161     0  1263     0     0]
 [   19  9152     6    14  1316]
 [ 1460     0  9853     0     0]
 [    1     9    21 10301     0]
 [    1  1752     0     0  9337]]
Overall Accuracy - Train:  0.8927669849632313
ROC score:  0.9828366141995234
Classification Report-                precision    recall  f1-score   support

           1       0.87      0.89      0.88     11424
           2       0.84      0.87      0.85     10507
           3       0.88      0.87      0.88     11313
           4       1.00      1.00      1.00     10332
           5       0.88      0.84      0.86     11090

    accuracy                           0.89     54666
   macro avg       0.89      0.89      0.89     54666
weighted avg       0.89      0.89      0.89     54666



Confusion Matrix - Train:  
 [[4319    0  522    0    0]
 [  10 3925    3    3  530]
 [ 633    0 4398    0    0]
 [   1    0   11 4430    1]
 [   0  675    0    2 3966]]
Overall Accuracy - Train:  0.89794698877459

#### Decision Tree

In [17]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()

In [18]:
dt.fit(X,y)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [19]:
mod=dt.fit(X_train,y_train)

train_pred=mod.predict(X_train)
train_prob=mod.predict_proba(X_train)

print('overall accuracy -Train: ',accuracy_score(y_train,train_pred))
print('confusion matrix:\n',confusion_matrix (y_train,train_pred))
print('AUC-train:',roc_auc_score(y_train,train_prob, multi_class='ovr'))
print('Classification Report- ',classification_report(y_train, y_train_pred))

test_pred=mod.predict(X_test)
test_prob=mod.predict_proba(X_test)
print('overall accuracy -Train: ',accuracy_score(y_test,test_pred))
print('confusion matrix:\n',confusion_matrix (y_test,test_pred))
print('AUC-train:',roc_auc_score(y_test,test_prob, multi_class='ovr'))
print('Classification Report- ',classification_report(y_test, y_test_pred))

overall accuracy -Train:  1.0
confusion matrix:
 [[11424     0     0     0     0]
 [    0 10507     0     0     0]
 [    0     0 11313     0     0]
 [    0     0     0 10332     0]
 [    0     0     0     0 11090]]
AUC-train: 1.0
Classification Report-                precision    recall  f1-score   support

           1       0.87      0.89      0.88     11424
           2       0.84      0.87      0.85     10507
           3       0.88      0.87      0.88     11313
           4       1.00      1.00      1.00     10332
           5       0.88      0.84      0.86     11090

    accuracy                           0.89     54666
   macro avg       0.89      0.89      0.89     54666
weighted avg       0.89      0.89      0.89     54666

overall accuracy -Train:  0.977805284049682
confusion matrix:
 [[4794    0   47    0    0]
 [   2 4249    0    0  220]
 [  58    0 4973    0    0]
 [   0    0    3 4440    0]
 [   0  189    0    1 4453]]
AUC-train: 0.9859833879724242
Classification Report- 

#### Random Forest - Super Star

In [20]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier(n_estimators = 200, n_jobs=-1)

rfc.fit(X_train, y_train)

y_train_pred = rfc.predict(X_train)
y_train_prob = rfc.predict_proba(X_train)

print('Confusion Matrix - Train: \n', confusion_matrix(y_train, y_train_pred))
print('\n')
print('Overall Accuracy - Train: ', accuracy_score(y_train, y_train_pred))
print('ROC score: ',roc_auc_score(y_train, y_train_prob, multi_class='ovr'))
print('Classification Report- ',classification_report(y_train, y_train_pred))

y_test_pred = rfc.predict(X_test)
y_test_prob = rfc.predict_proba(X_test)

print('\n')
print('Confusion Matrix - Test: \n', confusion_matrix(y_test, y_test_pred))
print('\n')
print('Overall Accuracy - Test: ', accuracy_score(y_test, y_test_pred))
print('ROC score: ',roc_auc_score(y_test, y_test_prob, multi_class='ovr'))
print('Classification Report- ',classification_report(y_test, y_test_pred))

Confusion Matrix - Train: 
 [[11424     0     0     0     0]
 [    0 10507     0     0     0]
 [    0     0 11313     0     0]
 [    0     0     0 10332     0]
 [    0     0     0     0 11090]]


Overall Accuracy - Train:  1.0
ROC score:  1.0
Classification Report-                precision    recall  f1-score   support

           1       1.00      1.00      1.00     11424
           2       1.00      1.00      1.00     10507
           3       1.00      1.00      1.00     11313
           4       1.00      1.00      1.00     10332
           5       1.00      1.00      1.00     11090

    accuracy                           1.00     54666
   macro avg       1.00      1.00      1.00     54666
weighted avg       1.00      1.00      1.00     54666



Confusion Matrix - Test: 
 [[4821    0   20    0    0]
 [   0 4399    0    0   72]
 [  13    0 5018    0    0]
 [   0    0    0 4443    0]
 [   0   54    0    0 4589]]


Overall Accuracy - Test:  0.9932135387767297
ROC score:  0.9999161418593

#### LightGBM

In [21]:
import lightgbm as lgb

In [22]:
lgbmc = lgb.LGBMClassifier()

lgbmc.fit(X_train, y_train)


y_train_pred = lgbmc.predict(X_train)
y_train_prob = lgbmc.predict_proba(X_train)

print('Confusion Matrix: ', '\n', confusion_matrix(y_train, y_train_pred))
print('Accuracy of Train: ',  accuracy_score(y_train, y_train_pred))
print('AUC of Train: ', roc_auc_score(y_train, y_train_prob,multi_class='ovr'))
print('Classification Report- ',classification_report(y_train, y_train_pred))

y_test_pred = lgbmc.predict(X_test)
y_test_prob = lgbmc.predict_proba(X_test)

print('\n'*2)
print('Confusion Matrix: ', '\n', confusion_matrix(y_test, y_test_pred))

print('Accuracy of Test: ',  accuracy_score(y_test, y_test_pred))
print('AUC of Test: ', roc_auc_score(y_test, y_test_prob,multi_class='ovr'))
print('Classification Report- ',classification_report(y_train, y_train_pred))

Confusion Matrix:  
 [[11424     0     0     0     0]
 [    0 10505     0     0     2]
 [    0     0 11313     0     0]
 [    0     0     0 10332     0]
 [    0     1     0     0 11089]]
Accuracy of Train:  0.9999451212819669
AUC of Train:  0.9999999911370212
Classification Report-                precision    recall  f1-score   support

           1       1.00      1.00      1.00     11424
           2       1.00      1.00      1.00     10507
           3       1.00      1.00      1.00     11313
           4       1.00      1.00      1.00     10332
           5       1.00      1.00      1.00     11090

    accuracy                           1.00     54666
   macro avg       1.00      1.00      1.00     54666
weighted avg       1.00      1.00      1.00     54666




Confusion Matrix:  
 [[4826    0   15    0    0]
 [   0 4441    0    0   30]
 [  16    0 5015    0    0]
 [   0    0    0 4443    0]
 [   0    7    0    0 4636]]
Accuracy of Test:  0.9970976140680353
AUC of Test:  0.99998278

#### K Fold Cross Validation

In [23]:
from sklearn.model_selection import cross_val_score

In [24]:
score= cross_val_score(lgbmc,X,y,cv=10)

In [25]:
score

array([0.94507042, 0.94353393, 0.83572343, 0.97797695, 0.97234315,
       0.99257267, 0.95697272, 0.99654245, 0.99513382, 0.92431809])

In [26]:
score.mean()

0.9540187649137236

#### Stratified K Fold Cross Validation

In [27]:
from sklearn.model_selection import StratifiedKFold

accuracy=[]

skf=StratifiedKFold(n_splits=10, random_state=None)
skf.get_n_splits(X,y)

for train_index, test_index in skf.split(X,y):
    print("Train:", train_index, "Validation:", test_index)
    X2_train,X2_test=X.iloc[train_index], X.iloc[test_index]
    y2_train,y2_test=y.iloc[train_index], y.iloc[test_index]
    
    lgbmc.fit(X2_train,y2_train)
    prediction=lgbmc.predict(X2_test)
    score=accuracy_score(prediction, y2_test)
    accuracy.append(score)
print(accuracy)

Train: [ 1627  1628  1629 ... 78092 78093 78094] Validation: [    0     1     2 ... 63932 63933 63934]
Train: [    0     1     2 ... 78092 78093 78094] Validation: [ 1627  1628  1629 ... 65505 65506 65507]
Train: [    0     1     2 ... 78092 78093 78094] Validation: [ 3254  3255  3256 ... 67079 67080 67081]
Train: [    0     1     2 ... 78092 78093 78094] Validation: [ 4881  4882  4883 ... 68653 68654 68655]
Train: [    0     1     2 ... 78092 78093 78094] Validation: [ 6508  6509  6510 ... 70227 70228 70229]
Train: [    0     1     2 ... 78092 78093 78094] Validation: [ 8135  8136  8137 ... 71800 71801 71802]
Train: [    0     1     2 ... 78092 78093 78094] Validation: [ 9761  9762  9763 ... 73373 73374 73375]
Train: [    0     1     2 ... 78092 78093 78094] Validation: [11387 11388 11389 ... 74946 74947 74948]
Train: [    0     1     2 ... 78092 78093 78094] Validation: [13013 13014 13015 ... 76519 76520 76521]
Train: [    0     1     2 ... 76519 76520 76521] Validation: [14639 14640

#### Hyper Parameter tuning

#### Grid Search

In [28]:
import sklearn
sklearn.metrics.SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'adjusted_rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_weighted'])

In [32]:
from sklearn.model_selection import GridSearchCV

dtc = DecisionTreeClassifier()

params = { 'max_depth' : [5,6,7,8,9,10] , 
           'min_samples_leaf' : [-2,-1,0,1,2] ,
           'min_samples_split': [8,9,10,11,12,13,14,15,16] ,
           'criterion' : ['gini' , 'entropy']
         }
gsearch=GridSearchCV(dtc,param_grid=params,cv=3,scoring='r2',n_jobs=-1)
gsearch.fit(X,y)

GridSearchCV(cv=3, error_score=nan,
             estimator=DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features=None,
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              presort='deprecated',
                                              random_state=None,
                                              splitter='best'),
             iid='deprecated', n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                     

In [33]:
gsearch.best_params_

{'criterion': 'gini',
 'max_depth': 10,
 'min_samples_leaf': 1,
 'min_samples_split': 11}

In [41]:
dtc=DecisionTreeClassifier(**gsearch.best_params_)
dtc.fit(X_train,y_train)

train_pred=dtc.predict(X_train)
train_prob=dtc.predict_proba(X_train)

print('overall accuracy -Train: ',accuracy_score(y_train,train_pred))
print('confusion matrix:\n',confusion_matrix (y_train,train_pred))
print('AUC-train:',roc_auc_score(y_train,train_prob, multi_class='ovr'))
print('Classification Report- ',classification_report(y_train, y_train_pred))

test_pred=dtc.predict(X_test)
test_prob=dtc.predict_proba(X_test)
print('overall accuracy -Train: ',accuracy_score(y_test,test_pred))
print('confusion matrix:\n',confusion_matrix (y_test,test_pred))
print('AUC-train:',roc_auc_score(y_test,test_prob, multi_class='ovr'))
print('Classification Report- ',classification_report(y_test, y_test_pred))

overall accuracy -Train:  0.9647495701167087
confusion matrix:
 [[11239     0   185     0     0]
 [    7 10015     0     0   485]
 [  163     0 11150     0     0]
 [   42     0     8 10282     0]
 [    0  1037     0     0 10053]]
AUC-train: 0.9960927448578865
Classification Report-                precision    recall  f1-score   support

           1       1.00      1.00      1.00     11424
           2       1.00      1.00      1.00     10507
           3       1.00      1.00      1.00     11313
           4       1.00      1.00      1.00     10332
           5       1.00      1.00      1.00     11090

    accuracy                           1.00     54666
   macro avg       1.00      1.00      1.00     54666
weighted avg       1.00      1.00      1.00     54666

overall accuracy -Train:  0.9581714968628623
confusion matrix:
 [[4745    0   96    0    0]
 [   1 4175    2    0  293]
 [  90    0 4941    0    0]
 [  18    0    3 4422    0]
 [   0  476    0    1 4166]]
AUC-train: 0.992209737

#### Randomized Search CV

In [37]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint as sp_randint

params={
    'max_depth':sp_randint(2,20),
    'min_samples_leaf':sp_randint(-5,5),
    'min_samples_split':sp_randint(-5,5),
    'criterion':['gini','entropy']
}
rsearch= RandomizedSearchCV(dtc,param_distributions=params,n_iter=200,cv=3,scoring='r2',n_jobs=-1)
rsearch.fit(X,y)

RandomizedSearchCV(cv=3, error_score=nan,
                   estimator=DecisionTreeClassifier(ccp_alpha=0.0,
                                                    class_weight=None,
                                                    criterion='gini',
                                                    max_depth=10,
                                                    max_features=None,
                                                    max_leaf_nodes=None,
                                                    min_impurity_decrease=0.0,
                                                    min_impurity_split=None,
                                                    min_samples_leaf=1,
                                                    min_samples_split=11,
                                                    min_weight_fraction_leaf=0.0,
                                                    presort='deprecated',
                                                    random_state=None,
           

In [38]:
rsearch.best_params_

{'criterion': 'entropy',
 'max_depth': 13,
 'min_samples_leaf': 3,
 'min_samples_split': 3}

In [40]:
dtc=DecisionTreeClassifier(**rsearch.best_params_)
dtc.fit(X_train,y_train)

train_pred=dtc.predict(X_train)
train_prob=dtc.predict_proba(X_train)

print('overall accuracy -Train: ',accuracy_score(y_train,train_pred))
print('confusion matrix:\n',confusion_matrix (y_train,train_pred))
print('AUC-train:',roc_auc_score(y_train,train_prob, multi_class='ovr'))
print('Classification Report- ',classification_report(y_train, y_train_pred))

test_pred=dtc.predict(X_test)
test_prob=dtc.predict_proba(X_test)
print('overall accuracy -Train: ',accuracy_score(y_test,test_pred))
print('confusion matrix:\n',confusion_matrix (y_test,test_pred))
print('AUC-train:',roc_auc_score(y_test,test_prob, multi_class='ovr'))
print('Classification Report- ',classification_report(y_test, y_test_pred))

overall accuracy -Train:  0.9865730069878901
confusion matrix:
 [[11415     0     9     0     0]
 [    0 10135     0     0   372]
 [  176     0 11137     0     0]
 [    0     0     0 10332     0]
 [    0   177     0     0 10913]]
AUC-train: 0.9990356212956607
Classification Report-                precision    recall  f1-score   support

           1       1.00      1.00      1.00     11424
           2       1.00      1.00      1.00     10507
           3       1.00      1.00      1.00     11313
           4       1.00      1.00      1.00     10332
           5       1.00      1.00      1.00     11090

    accuracy                           1.00     54666
   macro avg       1.00      1.00      1.00     54666
weighted avg       1.00      1.00      1.00     54666

overall accuracy -Train:  0.9739212087583764
confusion matrix:
 [[4823    0   18    0    0]
 [   0 4156    0    0  315]
 [  84    0 4947    0    0]
 [   0    0    1 4442    0]
 [   0  192    0    1 4450]]
AUC-train: 0.992043905